# Base configs
baseurl: /
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by John Sokol"
subtitle: "See the world through my eyes!"
author: "John Sokol"
header:
 title: "Photography"
 subtitle: "by Ram Patra"
footer:
 name: "John Sokol"
 bio: "I am a Data Scientist, Photographer, and Educator. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/johnsokol_"
  linkedin: "https://in.linkedin.com/in/sokolj"
  github: "https://www.github.com/sokolj1"
