# Base configs
baseurl: /
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-114520499-1"

# UI configs
title: "Photography by John Sokol"
subtitle:
author: "John Sokol"
header:
 title: "Photography"
 subtitle: "by John Sokol"
footer:
 name: "John Sokol"
 bio: "I am a Data Scientist, Photographer, and Educator."
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/johnsokol_"
  linkedin: "https://in.linkedin.com/in/sokolj"
  github: "https://www.github.com/sokolj1"
